
import { Consultant, ExpertCategory } from './types';

export const APP_NAME = "Tattaunawa360";
export const TAGLINE = "Find the Right Expert, Right Now.";
export const FOOTER_COPY = "Dan Mudi Digital Hub";

export const ALL_CATEGORIES: ExpertCategory[] = [
  'Programming & Tech',
  'Health & Medicine',
  'Architecture & Engineering',
  'Education & Teaching',
  'Business & Legal Advisory',
  'Design, Arts & Creativity',
  'Digital Marketing & SEO',
  'Finance & Accounting',
  'Writing & Translation',
  'Video & Animation',
  'Music & Audio',
  'Data Science & AI',
  'Lifestyle & Coaching',
  'Home Services & Trades',
  'Agriculture & Farming',
  'Real Estate',
  'Transportation & Logistics',
  'Events & Hospitality'
];

export const SUPPORTED_LANGUAGES = [
  { code: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'HA', name: 'Hausa', flag: '🇳🇬' },
  { code: 'FR', name: 'Français', flag: '🇫🇷' },
  { code: 'AR', name: 'العربية', flag: '🇸🇦' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
  { code: 'ZH', name: '中文', flag: '🇨🇳' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'HI', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'PT', name: 'Português', flag: '🇧🇷' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  EN: {
    home: 'Home',
    findExpert: 'Find Expert',
    region: 'My Region',
    dashboard: 'Dashboard',
    signIn: 'Sign In',
    heroTitle: 'Connect with Global',
    heroSubtitle: 'Verified Experts',
    heroDesc: 'Access professionals in Tech, Health, Law, and more instantly. Powered by AI matching to find your perfect fit.',
    joinExpert: 'Join as Expert',
    browseTitle: 'Browse Experts',
    regionTitle: 'Experts Near You',
    regionSubtitle: 'Connect with verified professionals in your city or nation.',
    regionPlaceholder: 'Select Region / City',
    searchPlaceholder: 'Type any profession (e.g. Plumber)...',
    clearFilters: 'Clear Filters',
    welcome: 'Welcome',
    noRegionResults: 'No local experts found in this region. Try the "Find Expert" tab for global options.'
  },
  HA: {
    home: 'Gida',
    findExpert: 'Nemo Masani',
    region: 'Yankina',
    dashboard: 'Gurin Aiki',
    signIn: 'Shiga',
    heroTitle: 'Haɗa da Kwararrun',
    heroSubtitle: 'Duniya da aka Tabbatar',
    heroDesc: 'Samun kwararru a fannin Fasaha, Lafiya, Sharia, da sauransu nan take. AI ne ke taimakawa wajen nemo wanda ya dace.',
    joinExpert: 'Shiga a Matsayin Masani',
    browseTitle: 'Bincika Masana',
    regionTitle: 'Masana a Kusa da Kai',
    regionSubtitle: 'Haɗa da kwararrun da aka tabbatar a garinku ko kasarku.',
    regionPlaceholder: 'Zaɓi Yanki / Birni',
    searchPlaceholder: 'Rubuta sana\'a (misali Makanike)...',
    clearFilters: 'Share Bincike',
    welcome: 'Barka da zuwa',
    noRegionResults: 'Ba a sami masana a wannan yankin ba. Gwada shafin "Nemo Masani" don binciken duniya.'
  },
  FR: {
    home: 'Accueil',
    findExpert: 'Trouver un Expert',
    region: 'Ma Région',
    dashboard: 'Tableau de Bord',
    signIn: 'Se Connecter',
    heroTitle: 'Connectez-vous avec des',
    heroSubtitle: 'Experts Vérifiés',
    heroDesc: 'Accédez instantanément à des professionnels de la technologie, de la santé, du droit et plus encore.',
    joinExpert: 'Devenir Expert',
    browseTitle: 'Parcourir les Experts',
    regionTitle: 'Experts Près de Chez Vous',
    regionSubtitle: 'Connectez-vous avec des professionnels vérifiés dans votre ville ou pays.',
    regionPlaceholder: 'Sélectionnez une région / ville',
    searchPlaceholder: 'Tapez une profession (ex. Plombier)...',
    clearFilters: 'Effacer les filtres',
    welcome: 'Bienvenue',
    noRegionResults: 'Aucun expert local trouvé dans cette région. Essayez l\'onglet "Trouver un Expert" pour des options mondiales.'
  },
  AR: {
    home: 'الرئيسية',
    findExpert: 'ابحث عن خبير',
    region: 'منطقتي',
    dashboard: 'لوحة القيادة',
    signIn: 'تسجيل الدخول',
    heroTitle: 'تواصل مع خبراء',
    heroSubtitle: 'عالميين معتمدين',
    heroDesc: 'الوصول إلى المتخصصين في التكنولوجيا والصحة والقانون والمزيد على الفور.',
    joinExpert: 'انضم كخبير',
    browseTitle: 'تصفح الخبراء',
    regionTitle: 'خبراء بالقرب منك',
    regionSubtitle: 'تواصل مع محترفين معتمدين في مدينتك أو بلدك.',
    regionPlaceholder: 'اختر المنطقة / المدينة',
    searchPlaceholder: 'أدخل مهنة (مثل سباك)...',
    clearFilters: 'مسح المرشحات',
    welcome: 'أهلاً بك',
    noRegionResults: 'لم يتم العثور على خبراء محليين في هذه المنطقة. جرب علامة التبويب "بحث عن خبير" للحصول على خيارات عالمية.'
  },
  ES: {
    home: 'Inicio',
    findExpert: 'Buscar Experto',
    region: 'Mi Región',
    dashboard: 'Panel',
    signIn: 'Iniciar Sesión',
    heroTitle: 'Conéctate con',
    heroSubtitle: 'Expertos Verificados',
    heroDesc: 'Acceda a profesionales en tecnología, salud, derecho y más al instante.',
    joinExpert: 'Únete como Experto',
    browseTitle: 'Explorar Expertos',
    regionTitle: 'Expertos Cerca de Ti',
    regionSubtitle: 'Conéctate con profesionales verificados en tu ciudad o país.',
    regionPlaceholder: 'Seleccionar región / ciudad',
    searchPlaceholder: 'Escriba una profesión (ej. Fontanero)...',
    clearFilters: 'Borrar Filtros',
    welcome: 'Bienvenido',
    noRegionResults: 'No se encontraron expertos locales en esta región. Pruebe la pestaña "Buscar Experto" para opciones globales.'
  },
  ZH: {
    home: '首页',
    findExpert: '寻找专家',
    region: '我的地区',
    dashboard: '仪表板',
    signIn: '登录',
    heroTitle: '联系全球',
    heroSubtitle: '认证专家',
    heroDesc: '即时接触科技、健康、法律等领域的专业人士。',
    joinExpert: '成为专家',
    browseTitle: '浏览专家',
    regionTitle: '您附近的专家',
    regionSubtitle: '与您所在城市或国家的认证专业人士联系。',
    regionPlaceholder: '选择地区/城市',
    searchPlaceholder: '输入职业（例如水管工）...',
    clearFilters: '清除筛选',
    welcome: '欢迎',
    noRegionResults: '在该地区未找到本地专家。请尝试“寻找专家”选项卡以获取全球选项。'
  },
  DE: {
    home: 'Startseite',
    findExpert: 'Experten finden',
    region: 'Meine Region',
    dashboard: 'Dashboard',
    signIn: 'Anmelden',
    heroTitle: 'Verbinden mit',
    heroSubtitle: 'Verifizierten Experten',
    heroDesc: 'Erhalten Sie sofortigen Zugang zu Fachleuten in Technik, Gesundheit, Recht und mehr.',
    joinExpert: 'Als Experte beitreten',
    browseTitle: 'Experten durchsuchen',
    regionTitle: 'Experten in Ihrer Nähe',
    regionSubtitle: 'Verbinden Sie sich mit verifizierten Fachleuten in Ihrer Stadt oder Ihrem Land.',
    regionPlaceholder: 'Region / Stadt wählen',
    searchPlaceholder: 'Beruf eingeben (z.B. Klempner)...',
    clearFilters: 'Filter löschen',
    welcome: 'Willkommen',
    noRegionResults: 'Keine lokalen Experten in dieser Region gefunden. Versuchen Sie den Reiter "Experten finden" für globale Optionen.'
  }
};

export const MOCK_CONSULTANTS: Consultant[] = [
  {
    id: '1',
    name: 'Dr. Amina Yusuf',
    title: 'Senior Cardiologist',
    category: 'Health & Medicine',
    bio: 'Over 15 years of experience in cardiovascular health and preventative medicine.',
    avatarUrl: 'https://picsum.photos/id/64/200/200',
    hourlyRate: 150,
    currency: 'USD',
    languages: ['English', 'Hausa', 'Arabic'],
    experienceYears: 15,
    rating: 4.9,
    reviewCount: 120,
    verified: true,
    availability: ['Mon', 'Wed', 'Fri'],
    location: 'Kano, Nigeria',
    reviews: []
  },
  {
    id: '2',
    name: 'Sarah Jenkins',
    title: 'Full Stack React Developer',
    category: 'Programming & Tech',
    bio: 'Specializing in scalable web applications using React, Node.js, and Cloud Infrastructure.',
    avatarUrl: 'https://picsum.photos/id/65/200/200',
    hourlyRate: 85,
    currency: 'USD',
    languages: ['English', 'Spanish'],
    experienceYears: 8,
    rating: 4.8,
    reviewCount: 45,
    verified: true,
    availability: ['Mon', 'Tue', 'Thu', 'Fri'],
    location: 'London, UK',
    reviews: []
  },
  {
    id: '3',
    name: 'Chinedu Okeke',
    title: 'Civil Engineer & Architect',
    category: 'Architecture & Engineering',
    bio: 'Structural engineering expert with a focus on sustainable urban planning.',
    avatarUrl: 'https://picsum.photos/id/91/200/200',
    hourlyRate: 120,
    currency: 'USD',
    languages: ['English', 'Igbo', 'French'],
    experienceYears: 12,
    rating: 4.7,
    reviewCount: 88,
    verified: true,
    availability: ['Weekends'],
    location: 'Lagos, Nigeria',
    reviews: []
  },
  {
    id: '4',
    name: 'Priya Patel',
    title: 'Corporate Legal Advisor',
    category: 'Business & Legal Advisory',
    bio: 'Helping startups navigate international business law and IP protection.',
    avatarUrl: 'https://picsum.photos/id/129/200/200',
    hourlyRate: 200,
    currency: 'USD',
    languages: ['English', 'Hindi'],
    experienceYears: 10,
    rating: 5.0,
    reviewCount: 200,
    verified: true,
    availability: ['Tue', 'Thu'],
    location: 'Mumbai, India',
    reviews: []
  },
  {
    id: '5',
    name: 'Jean-Luc Dubois',
    title: 'Creative Director',
    category: 'Design, Arts & Creativity',
    bio: 'Award-winning designer focusing on brand identity and UI/UX.',
    avatarUrl: 'https://picsum.photos/id/177/200/200',
    hourlyRate: 95,
    currency: 'USD',
    languages: ['French', 'English'],
    experienceYears: 7,
    rating: 4.6,
    reviewCount: 34,
    verified: true,
    availability: ['Mon', 'Fri'],
    location: 'Paris, France',
    reviews: []
  },
  {
    id: '6',
    name: 'Fatima Al-Fayed',
    title: 'Mathematics Professor',
    category: 'Education & Teaching',
    bio: 'Passionate educator specializing in advanced calculus and statistics for university students.',
    avatarUrl: 'https://picsum.photos/id/203/200/200',
    hourlyRate: 60,
    currency: 'USD',
    languages: ['Arabic', 'English'],
    experienceYears: 20,
    rating: 4.9,
    reviewCount: 310,
    verified: true,
    availability: ['Sat', 'Sun'],
    location: 'Cairo, Egypt',
    reviews: []
  }
];

export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia (Czech Republic)",
  "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini (fmr. 'Swaziland')", "Ethiopia",
  "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Holy See", "Honduras", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast",
  "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (formerly Burma)",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman",
  "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar",
  "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan",
  "Vanuatu", "Venezuela", "Vietnam",
  "Yemen",
  "Zambia", "Zimbabwe"
];
